### ISSUE TITLE
Como dev, quiero crear modelo, migración y validación de "academic_materials", para poder almacenar material académico

### ISSUE THREAD

**Issue by MaksiConGit** [MaksiConGit/proyecto-final-tercero#55]
Los campos requeridos:
- [x] id()
- [x] string('name') => 'required|max:255'
- [x] string('file_path') => 
- [x] string('file_size') =>
- [x] foreignId('subject_id') -> constrained() -> onUpdate('cascade') -> onDelete('restrict') => 'required|exists:subjects,id'
- [x] foreignId('teacher_id') -> constrained() -> onUpdate('cascade') -> onDelete('restrict') => 'required|exists:teachers,id'
- [x] boolean('is_deleted')->default(false) => 'boolean'
- [x] timestamps()

**Comment by LucasDLabo** [comment]
El campo _'name'_ deberia ser _unique_ o es irrelevante? 
Puede existir el caso de mismo nombre en el material pero diferente subject?

**Comment by MaksiConGit** [comment]
Habría que ver cómo manejamos este campo, todavía no sabemos cómo vamos a hacer con los archivos subidos.

**Comment by NRotili** [comment]
Hola!!! Acá un metido, ojo con los nombres de los archivos... 👀
